### ISSUE TITLE
QC for Oryza sativa

### ISSUE THREAD

**Issue by nspope** [popsim-consortium/stdpopsim#1458]
**PR for new species:** Oryza sativa #1453 

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

The QC reviewer should start a pull request that fills out the test stubs
with independently obtained values. The reviewer may look at the python code
for rationale provided in comments, but should ignore the actual code
as much as possible - comments in the code should give enough information
that it's obvious how to get the correct value from the provided references.
(In particular, we shouldn't copy-paste the value from the code into the test!)

- [ ] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [ ] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [ ] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [ ] Population size.
- [ ] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [ ] Genome reference assembly.
- [ ] Mutation rate.
- [ ] Recombination rate.
- [ ] Recombination map(s) (if relevant).
- [ ] Population size.
- [ ] Generation time.

The final PR should:
- [ ] fill out the test stubs
- [ ] delete the `pytest.mark.skip` lines that make the tests not run
- [ ] make sure they pass, talking to the original author to figure out discrepancies

**Comment by nspope** [comment]
Thanks for volunteering to QC, @minesrebollo!

**Comment by minesrebollo** [comment]
Hi! 

This is my progress so far on checking this:

- [x] Recombination rate
- [x] Genome assembly
- [x] Generation time

 I don't find the provided mutation rate number in the cited reference. I had previously used 3.2e-9 from [Yang et al. 2015](https://www.nature.com/articles/nature14649), what do you think about using this one instead @ornobalam? Or maybe you can point out where the provided number is on the Gaut et al. 1996. 

Citations are checked for:
- [x] Genome reference assembly
- [x] Recombination rate
- [x] Generation time

I will check the population size and demographic model later this week, sorry for the delay on doing this!

**Comment by ornobalam** [comment]
Hi! So, I picked up this mutation rate and citation from a few different papers (including [Salse et al. 2008](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2254919/), [Liu et al. 2017](https://academic.oup.com/mbe/article/34/4/908/2897207), and [Wang et al. 2016](https://www.sciencedirect.com/science/article/pii/S1674205216300557)). My best guess for how people calculated it comes from this passage in Gaut et al. 1996:
"The grass Adhl locus is estimated to evolve at a rate of 7.00 x 10-9 (±1.16 x 10-9) substitution per synonymous site per year, and the Adh2 locus is estimated to evolve at a rate of 5.99 x 10-9 (±1.13 x 10-9) substitution per synonymous site per year (Fig. 3A)."

They probably just calculated the mean of the rates for the two loci. Should've added all this as a comment!

I hadn't seen Yang et al. 2015, but I think it's clearly more robust. And using the 3.2e-9 rate for homozygotes makes sense as you see little heterozygosity in rice.

Thanks for going through these!

**Comment by minesrebollo** [comment]
Hi @ornobalam, your guess on how those authors got the recombination rate from Gaut et al. 1996 sounds good but if you agree that Yang et al. 2015 is more robust I think that is better too. Will you make that change in the commit or will it be part of my review? I am not sure about this process... 

For the population size, I see that you used the ratios of the effective population size of the current population to ancestral for the model with migration + bottleneck (v2 in table 2) but I wonder about the ancestral (rufipogon) population size estimate. They provide three different estimates, one from indica analyses, Nrufi = 57,471, other from tropical japonica, Nrufi = 118,110 and an independent one using the estimated scaled population silent mutation rates, where Nrufi = 135,500 but none is the one you used (150,000). Could you please point out what might I be missing? :)

Thanks!

**Comment by minesrebollo** [comment]
I now see that you specified this in `N_rufi = 12000 / (0.04 * 2)`, I wonder why did they not present this estimate in the paper too.

**Comment by minesrebollo** [comment]
Migration rates look good to me.

@nspope, after clarifying where the change in the mutation rate will be done and agreeing that the N_rufi used is the right one, do I need to start a pull request or that is all?

**Comment by ornobalam** [comment]
Hi! @minesrebollo, I am not sure about the process either, but I can change the mutation rate.

I agree it's not clear why they didn't present the 150,000 estimate in the paper. Especially because the migration model produced better fits for the different SFSs than the individual bottleneck models, which is why I used this estimate. My reason for not using the 135,000 estimate was that they calculated it from theta using a mutation rate of 1e-8.

There are of course other papers that provide Ne estimates for rufipogon. For instance, [Molina et al. 2011](https://www.pnas.org/doi/10.1073/pnas.1104686108) provides two estimates (~450,000 and ~260,000, both found in the supplementary information pdf). These are based on calculating theta from the number of segregating sites and then using different mutation rates to calculate Ne from theta=4Neu. It's not clear to me which estimate may be better across studies, but I do think the 150,000 makes the most sense to use from Caicedo et al.

(I have also been wondering about something else; the population size to be provided is described in the documentation like this: "the effective population size should represent the historical average effective population size". I interpreted this to mean ancestral effective population. Is that fair, @nspope ? The effective population sizes of the two rice subspecies japonica and indica (which are quite diverged but with gene flow) are distinct and the only way to have a historical effective size is through considering wild ancestral rice.)

If my interpretation of the effective population size here is correct, I propose to use the 150,000 estimate from Caicedo et al.

Thanks!

**Comment by nspope** [comment]
> @nspope, after clarifying where the change in the mutation rate will be done and agreeing that the N_rufi used is the right one, do I need to start a pull request or that is all?

Yup -- please start a pull request that fills out the test stubs in `tests/test_OrySat.py`, and fixes parameters in the various `catalog/OrySat/*.py` files. Thank you!

**Comment by nspope** [comment]
> the population size to be provided is described in the documentation like this: "the effective population size should represent the historical average effective population size". I interpreted this to mean ancestral effective population. Is that fair, @nspope ?

Yeah, good question! Rather than ancestral population size, I think what is meant here is a Ne value that produces levels of nucleotide diversity similar to that found in real data. For example, if you have a species that has gone through a very recent population decline, using its "ancestral Ne" for a global population size might make simulations unrealistically diverse. Maybe @igronau can clarify?

**Comment by petrelharp** [comment]
I agree with @nspope - however, there's not a single correct answer; the idea is to pick a reasonable value and document how you made the choice. (So, if it's not easy to find a documented value for nucleotide diversity (plus mut rate) to transform into an Ne then taking some other number from the demographic model - either modern or ancestral size - could be fine also.)

**Comment by minesrebollo** [comment]
Hi @ornobalam, I started the pull request (#1461) and some of the checks did not pass. I think it could be the mutation rate, I still see the one from Gaut et al. 1996 in the file instead of the one from Yang et al. 2015. Same with the reference for the mutation rate.

**Comment by ornobalam** [comment]
@minesrebollo Hi! Apologies, I just corrected the mutation rate and Ne.

@petrelharp and @nspope Thanks for clarifying! I am now using a value of Ne that is calculated from pi reported for Oryza sativa japonica.

**Comment by minesrebollo** [comment]
@ornobalam I still see the old one but maybe it is because it was not merged yet?

**Comment by ornobalam** [comment]
Hi! I've just created a new pull request. Please let me know if it didn't work.

**Comment by petrelharp** [comment]
The plan sounds good; for future reference it's okay to change the parameter values in the species definition in the same PR (e.g., if @minesrebollo had changed the original values also in this PR); at this point since we've all discussed and agreed, there's no need for @ornobalam to go do it. (What we want to avoid is the QC'er just changing the values without discussing and reaching consensus.)

**Comment by minesrebollo** [comment]
Hi @ornobalam ! I still see the old mutation rate in lines 13 and 37 of BottleneckMigration_3C07.csv
I don't think I can change it myself (maybe because I didn't start this pull request or because is merged yet?) or I just can't figure out how, sorry.
 
I see that there is a different citation for the population size now (Huang et al. 2012), could you please add how you calculate it from there as a comment? Population sizes from Caicedo et al. 2007 are still present in the demographic model but it is no longer cited for that, so what do you think about adding stdpopsim.CiteReason.POP_SIZE in that reference?

**Comment by ornobalam** [comment]
Hi @minesrebollo! I've fixed the csv (completely forgot the existence of that file) and placed the calculation of the Ne beneath the Huang et al. citation in species.py. As for the demographic model, I think the population sizes are population parameters for the model, so it might be okay for these to not be the same as the species Ne?

**Comment by minesrebollo** [comment]
Hi @ornobalam, great! I will make that change in my pull request and hopefully it will pass the checks. 

> As for the demographic model, I think the population sizes are population parameters for the model, so it might be okay for these to not be the same as the species Ne?

I would like to hear @petrelharp @nspope thoughts on this. Just to summarise, the Ne for the species is now 46,875 (O. sativa japonica's Ne based on pi reported in [Huang et al. 2012](https://doi.org/10.1038/nature11532)). For the demographic model, values from [Caicedo et al. 2007](https://doi.org/10.1371/journal.pgen.0030163) are used for the different groups: 

- Ancestral Ne = 150,000
- O. rufipogon Ne = 150,000
- O. sativa indica Ne = 40,500
- O. sativa tropical japonica Ne = 18,000 (differs from the species Ne based on pi)
- O. sativa indica & tropical japonica after origin Ne = 825

**Comment by nspope** [comment]
Thanks @minesrebollo and @ornobalam! Is the question if species population size should match a population size parameter in the demographic model? If so, the answer is "no, not necessarily" -- the species population size should be a representative value that gives diversity similar to what is seen in actual data. There's no requirement that this match a parameter value from a specific demographic model.

So, is the consensus that @ornobalam's PR #1462 is ready to go? If so, I'll take a look over it later today (codecov is broken, which is why the tests are failing). Then once it's merged, I'll post instructions for @minesrebollo to rebase #1461 on top of the fixes in #1462.

**Comment by minesrebollo** [comment]
@nspope, yes, #1462 is ready to go

**Comment by nspope** [comment]
Closed by #1461 and #1462
